# Generated by Django 2.1.7 on 2019-08-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
