# Generated by Django 2.1.7 on 2019-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
