# Generated by Django 2.1.7 on 2019-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_catalog_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
