# Generated by Django 2.1.7 on 2019-09-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190924_2156'),
        ('products', '0002_auto_20190827_1132'),
    ]

    operations = [
    ]
