# Generated by Django 2.1.7 on 2019-03-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190309_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.Categories'),
        ),
    ]
