# Generated by Django 2.1.7 on 2019-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20190926_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
