# Generated by Django 2.1.7 on 2019-04-15 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('kyc', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('metadata', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=20)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=50, null=True)),
                ('transactionId', models.CharField(max_length=50, null=True)),
                ('kyc', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.PaymentModes')),
            ],
        ),
    ]
