# Generated by Django 2.1.7 on 2019-04-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
