# Generated by Django 2.1.7 on 2019-03-10 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodes',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
