# Generated by Django 2.1.7 on 2019-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190410_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
