# Generated by Django 2.1.7 on 2019-04-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payments_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='transaction_id',
            new_name='transactionId',
        ),
    ]
