# Generated by Django 2.1.7 on 2019-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190410_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='kyc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
