# Generated by Django 2.1.7 on 2019-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payments_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='kyc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
