# Generated by Django 2.1.7 on 2019-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='name',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
