# Generated by Django 2.1.7 on 2019-03-08 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
