# Generated by Django 2.1.7 on 2019-09-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
    ]
