# Generated by Django 2.1.7 on 2019-11-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190926_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='delivery_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
