# Generated by Django 2.1.7 on 2019-11-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitems_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='buying_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='delivery_fee',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
