# Generated by Django 2.1.7 on 2019-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='facebook',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='instagram',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='soundcloud',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='twitter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='youtube',
            field=models.CharField(max_length=50),
        ),
    ]
