# Generated by Django 2.1.7 on 2019-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190706_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='bio',
            field=models.TextField(max_length=5000),
        ),
    ]
