# Generated by Django 2.1.7 on 2019-10-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clients_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Clients_category'),
        ),
    ]
