# Generated by Django 2.2.10 on 2020-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20191015_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=2000, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=2000, null=True)),
                ('vision', models.CharField(blank=True, max_length=2000, null=True)),
                ('mission', models.CharField(blank=True, max_length=2000, null=True)),
                ('identity', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
