# Generated by Django 2.2.10 on 2020-07-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='target_audience',
            new_name='target',
        ),
    ]
