# Generated by Django 2.2.10 on 2020-12-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200720_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('audio', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Clients')),
            ],
        ),
    ]
