# Generated by Django 2.1.7 on 2019-06-15 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('content', models.CharField(max_length=100)),
                ('tickets_link', models.URLField(max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Subtitle', models.CharField(max_length=50)),
                ('Content', models.TextField(max_length=1000)),
                ('Cover_Image', models.ImageField(blank=True, default='', upload_to='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
