# Generated by Django 2.1.7 on 2019-10-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Cover_Image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
