# Generated by Django 2.1.7 on 2019-10-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191015_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='Cover_Image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Subtitle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=500),
        ),
    ]
