# Generated by Django 2.1.7 on 2020-01-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cover_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='tickets_link',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
