<<<<<<< HEAD
# Generated by Django 2.1.7 on 2019-03-22 21:40
=======
# Generated by Django 2.1.7 on 2019-03-24 18:23
>>>>>>> 25dbfa5f1ed565f23d1a245fc6c50c3724ad7641

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190315_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
