# Generated by Django 2.1.7 on 2019-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='os',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
