# Generated by Django 2.1.7 on 2019-12-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_visitors_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='browser',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
